apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: test-argo-airflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: test-ewert
  source:
    repoURL: https://github.com/apache/airflow.git
    targetRevision: "2.7.1"
    chart: airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow-ewert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
      # - "ServerSideApply=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"